import type { ProjectCase } from "./project-cases";

type ProjectTranslation = Pick<ProjectCase,
  "type" | "service" | "projectType" | "imageAlt" | "heroMockupAlt" |
  "showcaseDesktopAlt" | "showcaseTabletAlt" | "showcaseMobileAlt" |
  "intro" | "summaryTitle" | "summary" | "visitLabel" | "stages" | "result"
>;

export const catalanProjectCopy: Record<string, ProjectTranslation> = {
  "wild-roots": {
    type: "Marca i web",
    service: "Comerç electrònic, direcció visual, SEO",
    projectType: "Botiga en línia editorial",
    imageAlt: "Mockup d'una botiga en línia editorial amb joieria artesanal i productes naturals",
    heroMockupAlt: "Mockup de la botiga en línia orgànica en un portàtil i un mòbil sobre una base de pedra",
    showcaseDesktopAlt: "Mockup d'escriptori de La Terra Viva amb un catàleg de receptes a la pantalla",
    showcaseTabletAlt: "Mockup de tauleta de La Terra Viva amb un catàleg de pastes artesanes",
    showcaseMobileAlt: "Mockup de mòbil de La Terra Viva amb productes ecològics i de proximitat",
    intro: "Una botiga en línia d'estil editorial per a una marca orgànica que necessitava presentar els seus productes com a peces cuidades.",
    summaryTitle: "Una botiga en línia de productes ecològics amb essència natural",
    summary: "La Terra Viva necessitava un web capaç de presentar productes orgànics, ecològics i de proximitat amb una imatge cuidada, clara i coherent. Vaig treballar una estructura visual senzilla per ordenar l'oferta, destacar els valors de la marca i facilitar que l'usuari entengués ràpidament quins productes podia descobrir, mantenint sempre una experiència neta, adaptable i fàcil de recórrer.",
    visitLabel: "Veure l'enfocament",
    stages: [
      { title: "Estratègia", text: "Definició de categories, recorregut de compra i to visual." },
      { title: "Disseny", text: "Sistema editorial amb detalls orgànics i un ritme visual net." },
      { title: "Desenvolupament", text: "Maquetació adaptable, lleugera i fàcil de mantenir." },
      { title: "Resultat", text: "Una botiga clara, delicada i preparada per créixer." },
    ],
    result: "La marca guanya una presència digital més cuidada, amb una experiència que acompanya l'usuari des de la inspiració fins a la compra.",
  },
  "solena-retreat": {
    type: "Disseny web",
    service: "Disseny web, serveis, reserves",
    projectType: "Web de serveis",
    imageAlt: "Mockup d'una pàgina web per a una perruqueria amb serveis de cabell i tractaments",
    heroMockupAlt: "Mockup principal de Glamour Perruquers en ordinador i mòbil",
    showcaseDesktopAlt: "Mockup d'escriptori de Glamour Perruquers amb els serveis de perruqueria",
    showcaseTabletAlt: "Mockup de tauleta de Glamour Perruquers amb serveis i tractaments",
    showcaseMobileAlt: "Mockup de mòbil de Glamour Perruquers amb els serveis de perruqueria",
    intro: "Un web de serveis per a una perruqueria, creat per ordenar els tractaments i guiar cap a la reserva amb confiança.",
    summaryTitle: "Un web clar per mostrar els serveis i generar confiança",
    summary: "Glamour Perruquería necessitava una presència digital que transmetés professionalitat i proximitat des del primer moment. Vaig organitzar els serveis perquè l'usuari entengués ràpidament què ofereix el saló, vaig plantejar una imatge inicial amb un vídeo de fons per aportar moviment i vaig cuidar una composició neta amb fotografies protagonistes i un disseny adaptable perquè l'experiència fos clara tant al mòbil com a l'ordinador.",
    visitLabel: "Veure l'enfocament",
    stages: [
      { title: "Estratègia", text: "Organització dels serveis i els missatges principals." },
      { title: "Disseny", text: "Direcció visual neta, femenina i accessible." },
      { title: "Desenvolupament", text: "Seccions modulars per editar el contingut amb facilitat." },
      { title: "Resultat", text: "Un web clar que genera confiança i facilita la reserva." },
    ],
    result: "El projecte converteix una oferta de serveis en una experiència ordenada, visual i fàcil de recórrer des del mòbil.",
  },
  "forest-whisper": {
    type: "Disseny web",
    service: "Disseny web, direcció visual, disseny adaptable",
    projectType: "Web de serveis",
    imageAlt: "Mockup d'una pàgina web adaptable per a un centre de massatges i benestar",
    heroMockupAlt: "Mockup principal de Serenia Masajes en ordinador i mòbil",
    showcaseDesktopAlt: "Mockup d'escriptori de Serenia Masajes amb tractaments a la pantalla",
    showcaseTabletAlt: "Mockup de tauleta de Serenia Masajes amb la llista de tractaments",
    showcaseMobileAlt: "Mockup de mòbil de Serenia Masajes amb serveis i botó de reserva",
    intro: "Un web de serveis creat per transmetre calma, confiança i benestar des del primer moment.",
    summaryTitle: "Una experiència digital tranquil·la per a un espai de benestar",
    summary: "El projecte organitza els tractaments de Serenia amb una estructura clara, una estètica suau i crides a la reserva visibles. La direcció visual busca que l'usuari entengui ràpidament els serveis i senti una experiència propera abans de demanar cita.",
    visitLabel: "Veure l'experiència",
    stages: [
      { title: "Estratègia", text: "Definició d'una navegació senzilla per presentar els tractaments, els beneficis i la reserva sense friccions." },
      { title: "Disseny", text: "Una composició visual serena, orgànica i professional, alineada amb un negoci de benestar." },
      { title: "Desenvolupament", text: "Un web adaptable preparat per veure's amb claredat al mòbil, la tauleta i l'ordinador." },
      { title: "Resultat", text: "Una experiència clara i calmada que ajuda el client a conèixer els serveis i reservar amb confiança." },
    ],
    result: "Un web pensat per mostrar els tractaments de massatge amb claredat, coherència visual i una navegació senzilla des de qualsevol dispositiu.",
  },
  "alba-galeria-de-arte": {
    type: "Comerç electrònic",
    service: "Comerç electrònic, disseny web, direcció visual",
    projectType: "Botiga d'art en línia",
    imageAlt: "Imatge de referència per a una botiga en línia de peces artístiques úniques",
    heroMockupAlt: "Mockup d'Alba Galería de Arte en ordinador i mòbil amb peces decoratives",
    showcaseDesktopAlt: "Portàtil amb el catàleg d'obres d'Alba Galería de Arte",
    showcaseTabletAlt: "Tauleta amb el catàleg d'Alba Galería de Arte",
    showcaseMobileAlt: "Mòbil amb una obra del catàleg d'Alba Galería de Arte",
    intro: "Una galeria d'art en línia creada per descobrir i comprar peces úniques des de qualsevol dispositiu.",
    summaryTitle: "Una botiga en línia per acostar l'art a noves mirades",
    summary: "Alba Galería de Arte necessitava un espai digital que transmetés el valor de cada obra i facilités la compra en línia sense perdre la sensibilitat d'una visita a una galeria. La proposta organitza les peces de manera clara, dona protagonisme a la imatge i acompanya el visitant des del descobriment fins a la compra amb una experiència cuidada i adaptable.",
    visitLabel: "Veure l'enfocament",
    stages: [
      { title: "Estratègia", text: "Definició de categories, fitxes d'obra i recorregut de compra." },
      { title: "Disseny", text: "Direcció visual sòbria perquè cada peça sigui la protagonista." },
      { title: "Desenvolupament", text: "Comerç electrònic adaptable pensat per descobrir i comprar amb facilitat." },
      { title: "Resultat", text: "Una galeria digital clara, elegant i preparada per créixer." },
    ],
    result: "Una experiència de compra en línia que presenta cada obra amb calma, context i una navegació senzilla des del mòbil, la tauleta i l'ordinador.",
  },
};
